[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/",

    # Contributor names aren't typos.
    ".mailmap",

    # File suffixes aren't typos.
    "crates/theme/src/icon_theme.rs",

    # Fuzzy matching and editor fixtures rely on partial typing and custom in-string syntax.
    "crates/fuzzy_nucleo/src/strings.rs",

    # Protols is the name of the language server.
    "crates/proto/",

    # typos-cli doesn't understand our `vˇariable` markup
    "crates/editor/src/hover_links.rs",

    # Macos apis
    "crates/gpui_macos/src/dispatcher.rs",

    # Tests contain `baˇr` that cause `"ba" should be "by" or "be".`-like false-positives
    "crates/editor/src/document_symbols.rs",
]

[default]
extend-ignore-re = [
    # PNG is a file format, not a typo
    "PNG",
    'cl\[ist]',
    '\[lan\]guage',
    '"ba"',
    "doas",
    # ProtoLS crate with tree-sitter Protobuf grammar.
    "protols",
    # x11rb SelectionNotifyEvent struct field
    "requestor",
    # macOS version
    "Big Sur",
    # Not an actual typo but an intentionally invalid color, in `color_extractor`
    "#fof",
    # Stripped version of reserved keyword `type`
    "typ",
    # AMD GPU Services
    "ags",
    # AMD GPU Services
    "AGS",
    # "noet" is a vim variable (ideally to ignore locally)
    "noet",
    # Yarn Plug'n'Play
    "PnP",
    # `image` crate method: Delay::from_numer_denom_ms
    "numer"
]
check-filename = true
