use std::sync::Arc;

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Eq, Copy, Clone, Serialize, Deserialize)]
pub enum IconName {
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpRight,
    Backspace,
    Chat,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronUpDown,
    Close,
    Command,
    Control,
    Copy,
    Dash,
    Escape,
    ExpandDown,
    ExpandUp,
    ExpandVertical,
    Eye,
    EyeOff,
    FileLock,
    FileMarkdown,
    FileTree,
    HistoryRerun,
    Info,
    LoadCircle,
    Maximize,
    Minimize,
    Option,
    PageDown,
    PageUp,
    Person,
    Pin,
    Plus,
    ReplyArrowRight,
    Return,
    Shift,
    Sliders,
    Space,
    Sparkle,
    Split,
    Tab,
    Stop,
    Warning,
    XCircle,
}

impl IconName {
    /// Returns the path to this icon.
    pub fn path(&self) -> Arc<str> {
        let file_stem = match self {
            Self::ArrowDown => "arrow_down",
            Self::ArrowLeft => "arrow_left",
            Self::ArrowRight => "arrow_right",
            Self::ArrowUp => "arrow_up",
            Self::ArrowUpRight => "arrow_up_right",
            Self::Backspace => "backspace",
            Self::Chat => "chat",
            Self::Check => "check",
            Self::ChevronDown => "chevron_down",
            Self::ChevronRight => "chevron_right",
            Self::ChevronUpDown => "chevron_up_down",
            Self::Close => "close",
            Self::Command => "command",
            Self::Control => "control",
            Self::Copy => "copy",
            Self::Dash => "dash",
            Self::Escape => "escape",
            Self::ExpandDown => "expand_down",
            Self::ExpandUp => "expand_up",
            Self::ExpandVertical => "expand_vertical",
            Self::Eye => "eye",
            Self::EyeOff => "eye_off",
            Self::FileLock => "file_lock",
            Self::FileMarkdown => "file_markdown",
            Self::FileTree => "file_tree",
            Self::HistoryRerun => "history_rerun",
            Self::Info => "info",
            Self::LoadCircle => "load_circle",
            Self::Maximize => "maximize",
            Self::Minimize => "minimize",
            Self::Option => "option",
            Self::PageDown => "page_down",
            Self::PageUp => "page_up",
            Self::Person => "person",
            Self::Pin => "pin",
            Self::Plus => "plus",
            Self::ReplyArrowRight => "reply_arrow_right",
            Self::Return => "return",
            Self::Shift => "shift",
            Self::Sliders => "sliders",
            Self::Space => "space",
            Self::Sparkle => "sparkle",
            Self::Split => "split",
            Self::Tab => "tab",
            Self::Stop => "stop",
            Self::Warning => "warning",
            Self::XCircle => "x_circle",
        };
        format!("icons/{file_stem}.svg").into()
    }
}
