[book]
authors = ["Zen Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "Zen"

[output.html]
no-section-label = true
preferred-dark-theme = "ayu"
default-theme = "light"
git-repository-url = ""
