[package]
name = "grammars"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[lib]
path = "src/grammars.rs"

[dependencies]
language_core.workspace = true
rust-embed.workspace = true
anyhow.workspace = true
toml.workspace = true
util.workspace = true

tree-sitter = { workspace = true, optional = true }
tree-sitter-json = { workspace = true, optional = true }
tree-sitter-md = { workspace = true, optional = true }
tree-sitter-regex = { workspace = true, optional = true }

[features]
load-grammars = [
    "tree-sitter",
    "tree-sitter-json",
    "tree-sitter-md",
    "tree-sitter-regex",
]
test-support = ["load-grammars"]
